"""intigriti.py — a Python wrapper for the Intigriti API."""

from __future__ import annotations

from intigriti.enums import (
    ActivityType,
    ConfidentialityLevel,
    DomainTier,
    DomainType,
    ProgramStatus,
    ProgramType,
)
from intigriti.exceptions import (
    IntigritiAPIError,
    IntigritiAuthenticationError,
    IntigritiConflictError,
    IntigritiError,
    IntigritiNotFoundError,
    IntigritiPermissionError,
    IntigritiRateLimitError,
    IntigritiServerError,
    IntigritiServiceUnavailableError,
    IntigritiValidationError,
)
from intigriti.models import (
    Activity,
    Attachment,
    Domain,
    Enumeration,
    Money,
    Page,
    Payout,
    Program,
    ProgramActivity,
    ProgramDetail,
    ProgramDomains,
    ProgramRulesOfEngagement,
    ProgramWebLinks,
    RulesOfEngagement,
    Skill,
    TestingRequirements,
    Version,
    VersionWithAttachments,
)

__version__ = '0.1.0'

__all__ = [
    'Activity',
    'ActivityType',
    'Attachment',
    'ConfidentialityLevel',
    'Domain',
    'DomainTier',
    'DomainType',
    'Enumeration',
    'IntigritiAPIError',
    'IntigritiAuthenticationError',
    'IntigritiConflictError',
    'IntigritiError',
    'IntigritiNotFoundError',
    'IntigritiPermissionError',
    'IntigritiRateLimitError',
    'IntigritiServerError',
    'IntigritiServiceUnavailableError',
    'IntigritiValidationError',
    'Money',
    'Page',
    'Payout',
    'Program',
    'ProgramActivity',
    'ProgramDetail',
    'ProgramDomains',
    'ProgramRulesOfEngagement',
    'ProgramStatus',
    'ProgramType',
    'ProgramWebLinks',
    'RulesOfEngagement',
    'Skill',
    'TestingRequirements',
    'Version',
    'VersionWithAttachments',
    '__version__',
]
